### ISSUE TITLE
set up Gitlab to use my casdoor LDAP service for authentication, but I couldn't get it to work

### ISSUE THREAD

**Issue by aosolao** [casbin/casdoor#2056]
I tried to set up Gitlab to use my casdoor LDAP service for authentication, but I couldn't get it to work.
The test user I'm trying to log in with belongs to the lianjian organization.
What have I configured incorrectly?
Below are Gitlab's configurations.

```
gitlab_rails['ldap_enabled'] = true                                               
gitlab_rails['prevent_ldap_sign_in'] = false                                              
                                                                                  
###! **remember to close this block with 'EOS' below**                            
gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'                                             
  main: # 'main' is the GitLab 'provider ID' of this LDAP server                  
    label: 'LDAP'                                                                 
    host: '10.233.62.2'                                                                        
    port: 389                                                                     
    uid: 'uid'                                                                    
    bind_dn: 'cn=admin,ou=built-in,dc=example,dc=com'                                                    
    password: '123'                                                                                           
    encryption: 'plain' # "start_tls" or "simple_tls" or "plain"                  
#     verify_certificates: true                                                   
#     smartcard_auth: false                                                       
    active_directory: false                                                       
    allow_username_or_email_login: true                                           
#     lowercase_usernames: false                                                  
    block_auto_created_users: false                                                                    
    base: 'ou=lianjian,dc=example,dc=com'                       
    user_filter: ''                                                          
    ## EE only                                                  
    group_base: ''                                                       
    admin_group: ''                                             
    sync_ssh_keys: false               
EOS
```

![Snipaste_2023-07-11_15-33-43](https://github.com/casdoor/casdoor/assets/30789071/c1534fcf-6106-4ef7-95b2-79a4c17e547b)

**Comment by aosolao** [comment]
![Snipaste_2023-07-11_16-38-52](https://github.com/casdoor/casdoor/assets/30789071/9429b1c3-c819-450f-b947-7dc9c0b386b9)

The gitlab logs contain the following message, indicating that the email cannot be blank, but this user has already set an Email.

```
{"severity":"INFO","time":"2023-07-11T07:56:43.753Z","correlation_id":"01H51Z7QZ9XXQA4XW7V8HPS2CE","meta.caller_id":"Ldap::OmniauthCallbacksController#ldapmain","meta.remote_ip":"10.233.70.0","meta.feature_category":"system_access","meta.client_id":"ip/10.233.70.0","message":"(LDAP) Error saving user cn=xuqing,ou=lianjian,dc=192.168.11.251,dc=com (): [\"Email can't be blank\"]"}
```

**Comment by aosolao** [comment]
The gitlab logs contain the following message, indicating that the email cannot be blank, but this user has already set an Email.

```
{"severity":"INFO","time":"2023-07-11T07:56:43.753Z","correlation_id":"01H51Z7QZ9XXQA4XW7V8HPS2CE","meta.caller_id":"Ldap::OmniauthCallbacksController#ldapmain","meta.remote_ip":"10.233.70.0","meta.feature_category":"system_access","meta.client_id":"ip/10.233.70.0","message":"(LDAP) Error saving user cn=xuqing,ou=lianjian,dc=192.168.11.251,dc=com (): [\"Email can't be blank\"]"}
```

![Snipaste_2023-07-11_16-38-52](https://github.com/casdoor/casdoor/assets/30789071/cb4dac70-1ba1-46c4-8de3-5a5d528bc0fd)

**Comment by hsluoyz** [comment]
@aosolao why didn't you try connecting GitLab to Casdoor via OIDC? https://casdoor.org/docs/integration/ruby/gitlab

**Comment by aosolao** [comment]
> @aosolao why didn't you try connecting GitLab to Casdoor via OIDC? https://casdoor.org/docs/integration/ruby/gitlab

As new users logging into GitLab using OIDC require GitLab administrators to create an additional account in GitLab and associate it with their Casdoor account, whereas using LDAP to log into GitLab automatically creates the account without the need for any additional action from the administrator. Hence, LDAP is chosen to connect to GitLab.

**Comment by leoil** [comment]
Hi, can you elaberate on how you set-up gitlab and the casdoor ldap sever?
I got this error when logging with LDAP.
![image](https://github.com/casdoor/casdoor/assets/31148569/ae252ec0-a1d6-4839-b20e-44cecd709325)
```
{"severity":"ERROR","time":"2023-07-28T13:41:49.076Z","correlation_id":"01H6EBQVBMR82RYWHV26VDPRZ9",
"message":"(ldapmain) Authentication failure! invalid_credentials: 
OmniAuth::Strategies::LDAP::InvalidCredentialsError, Invalid credentials for admin"}

```

This is my  Gitlab's configurations:
```rb
gitlab_rails['ldap_enabled'] = true
gitlab_rails['prevent_ldap_sign_in'] = false

###! **remember to close this block with 'EOS' below**
gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
  main: # 'main' is the GitLab 'provider ID' of this LDAP server
    label: 'LDAP'
    host: '10.0.2.2'
    port: 389

    uid: 'sAMAccountName'
    bind_dn: 'cn=admin,ou=built-in,dc=example,dc=com'
    password: '123'
    encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
    #verify_certificates: true
    #smartcard_auth: false
    active_directory: true
    allow_username_or_email_login: false
    lowercase_usernames: false
    block_auto_created_users: false
    base: ''
    user_filter: ''
    ## EE only
    group_base: ''
    admin_group: ''
    sync_ssh_keys: false
EOF
```

**Comment by aosolao** [comment]
@hsluoyz Has there been any progress on this issue?

**Comment by hsluoyz** [comment]
@aosolao can you debug GitLab to see which field is missing from Casdoor? We are familar with Casdoot but not familiar with GitLab. So it's very hard for us to debug GitLab issues

**Comment by aosolao** [comment]
Can Casdoor's own LDAP server provide services externally?
Are the two configurations I posted above correct?

```
 bind_dn: 'cn=admin,ou=built-in,dc=example,dc=com' 
 base: 'ou=lianjian,dc=example,dc=com' 
```

@hsluoyz

**Comment by hsluoyz** [comment]
@aosolao we failed to debug GitLab because being not familiar with its code.

**Comment by aosolao** [comment]
> @aosolao we failed to debug GitLab because being not familiar with its code.

It's not just Gitlab, other LDAP clients also cannot connect to Casdoor's LDAP service.
I'm not sure if it's because I configured the wrong bind_dn, or if Casdoor's LDAP service itself has an issue.

**Comment by hsluoyz** [comment]
@aosolao can you give an reproducable example for another simple LDAP client?

1. How to configure
2. What you expect
3. What you got

**Comment by aosolao** [comment]
![image](https://github.com/casdoor/casdoor/assets/30789071/5529c406-e0be-4733-b1be-6a2260e6c9a1)
![image](https://github.com/casdoor/casdoor/assets/30789071/faa86e2e-16ae-40b2-b002-c1b20bedcf35)

The above screenshots show accessing the casdoor LDAP service using the ApacheDirectoryStudio software and the error message screenshot.

Under normal circumstances, it should be able to connect successfully and retrieve user information from the ldap server.

For example, the screenshot below shows the results that can be seen when connecting to an openldap-server using the same software.

![image](https://github.com/casdoor/casdoor/assets/30789071/1b73edf4-5dc0-47dd-b8a0-d94e2058a08e)

**Comment by ganisback** [comment]
me too, I found the search result does not contain the uid field
```
root@m1:~# ldapsearch -H ldap://xxxxxxxx:1389  -x -D "cn=admin,ou=built-in,dc=test,dc=com"  -w "xxxxxx"  -LLL -b "ou=test,dc=G1,dc=com"
dn: cn=test1,ou=G1,dc=example,dc=com

dn: cn=test2,ou=G1,dc=example,dc=com
```

**Comment by ganisback** [comment]
@aosolao I checked the source code, they did not return the UID filed, that's why we can not integrate with ldap

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/pull/2500 and https://github.com/casbin/casdoor/pull/2508

@aosolao @ganisback hi, can you try the latest version again?

**Comment by keac** [comment]
![image](https://github.com/casbin/casdoor/assets/16091665/3f809478-5ea9-4173-86c4-d2e1c9de7ea2)
Use  latest version can not work

**Comment by hsluoyz** [comment]
@keac create new issue

**Comment by xtutu** [comment]
Access denied for your LDAP account.

still have this issue  in verion: [v1.969.0](https://github.com/casdoor/casdoor/releases/tag/v1.969.0)


@aosolao  Have you solved it?

**Comment by xtutu** [comment]
@hsluoyz I'm facing the same problem with the newest version.

**Comment by hsluoyz** [comment]
@xtutu you should create new issue given this issue is very old. And prove that it's Casdoor's bug instead of your own fault

**Comment by xtutu** [comment]
@hsluoyz 
I create a new issue: https://github.com/casdoor/casdoor/issues/3972
